name: pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.6
      - name: Install dependencies
        run: npm ci
      - name: List files
        run: ls -la
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.6
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: List files
        run: ls -la


